version: '3'
services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goodsntrucks

  # truck-location-reloads:
  #   build:
  #     context: https://github.com/Myortv/truck-location-reloads.git
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres
  #     - fastapi-server
  #   volumes:
  #     - ./truck_location_reloads.py:/app/truck_location_reloads.py
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/goodsntrucks
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=goodsntrucks

  fastapi-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - 8000:8000
    # volumes:
    #   - ./app:/app
    #   - ./prestart.sh:/prestart.sh
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/goodsntrucks
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goodsntrucks
